version: '3.3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: eventflow
      POSTGRES_USER: twoj_user
      POSTGRES_PASSWORD: twoje_haslo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
